CREATE TABLE PLANINFO (
	P_ROWNUM	NUMBER	NOT NULL,
	M_NICKNAME	VARCHAR2(18)	NOT NULL,
	P_TITLE	VARCHAR2(255)	NOT NULL,
	P_FIRSTDATE	DATE	NOT NULL,
	P_LASTDATE	DATE	NOT NULL,
	T_NAMELIST	VARCHAR2(255)	NULL,
	P_REGDATE	DATE	NOT NULL,
	P_LIKE	NUMBER	NOT NULL,
    P_PUBLIC NUMBER(1) NOT NULL
);

CREATE TABLE MEMBERINFO (
	M_NICKNAME	VARCHAR2(18)	NOT NULL,
	M_PASSWORD	VARCHAR2(50)	NOT NULL,
	M_BIRTHYEAR	NUMBER(4)	NOT NULL,
	M_GENDER	NUMBER(1)	NOT NULL,
	M_JOINDATE	DATE	NOT NULL
);

CREATE TABLE TAGLIST (
	T_NAME	VARCHAR2(30)	NOT NULL,
	T_HIT	NUMBER	NOT NULL
);

CREATE TABLE PLANDETAIL (
	P_ROWNUM	NUMBER	NOT NULL,
	P_TRIPDAY	NUMBER	NOT NULL,
  	P_TRIPDATE	DATE	NOT NULL,
    P_SEQUENCE NUMBER NOT NULL,
	S_SERIALNUM	VARCHAR2(18)	NOT NULL,
	P_SPOTNAME	VARCHAR2(255)	NOT NULL
);

CREATE TABLE SPOTDETAIL (
	S_SERIALNUM	VARCHAR2(50)	NOT NULL,
	S_NAME	VARCHAR2(255)	NOT NULL
);

CREATE TABLE ACCOMMODATION (
	S_SERIALNUM	VARCHAR2(18)	NOT NULL,
	A_TYPE	VARCHAR2(20)	NULL,
	A_NAME	VARCHAR2(255)	NOT NULL,
    A_PNUMBER VARCHAR2(255)     NOT NULL,
	A_LOCATION	VARCHAR2(255)	NOT NULL,
	A_CHECKIN	VARCHAR2(10)	NOT NULL,
	A_CHECKOUT	VARCHAR2(10)	NOT NULL,
	A_PHOTO	VARCHAR2(255)	NULL
);

CREATE TABLE RESTAURANT (
	S_SERIALNUM	VARCHAR2(18)	NOT NULL,
	R_TYPE	VARCHAR2(20)	NULL,
	R_NAME	VARCHAR2(255)	NOT NULL,
    R_PNUMBER VARCHAR2(255)     NOT NULL,
	R_LOCATION	VARCHAR2(255)	NOT NULL,
	R_OPENTIME	VARCHAR2(10)	NOT NULL,
	R_CLOSETIME	VARCHAR2(10)	NOT NULL,
	R_PHOTO	VARCHAR2(255)	NOT NULL
);

CREATE TABLE EVENT (
	S_SERIALNUM	VARCHAR2(18)	NOT NULL,
	E_NAME	VARCHAR2(255)	NOT NULL,
    E_VENUE VARCHAR2(255)   NOT NULL,
    E_PNUMBER VARCHAR2(255)     NOT NULL,
    E_LOCATION	VARCHAR2(255)	NOT NULL,
	E_STARTDATE	DATE,
	E_ENDDATE	DATE,
	E_PHOTO	VARCHAR2(255)	NOT NULL,
	E_URL	VARCHAR2(2000)	NULL
);

CREATE TABLE TRAFFIC (
    S_SERIALNUM VARCHAR(18) NOT NULL,
    TF_TYPE VARCHAR2(20) NOT NULL, 
    TF_NAME VARCHAR2(255) NOT NULL,
    TF_PNUMBER VARCHAR2(255) NOT NULL,
    TF_LOCATION VARCHAR2(255) NOT NULL,
    TF_PHOTO VARCHAR2(255) NOT NULL
);

CREATE TABLE LIKEINFO(
    M_NICKNAME VARCHAR2(18) NOT NULL,
    P_ROWNUM NUMBER NOT NULL,
    M_AGERANGE NUMBER(3) NOT NULL,
    M_GENDER NUMBER(1) NOT NULL
);

--PLANINFO 테이블
--1. 기본키 설정
ALTER TABLE PLANINFO ADD CONSTRAINT PK_PLANINFO PRIMARY KEY (
	P_ROWNUM
);
--MEMBERINFO 테이블 기본키 설정
ALTER TABLE MEMBERINFO ADD CONSTRAINT PK_MEMBERINFO PRIMARY KEY (
	M_NICKNAME
);
--SPOTDETAIL 기본키 설정
ALTER TABLE SPOTDETAIL ADD CONSTRAINT PK_SPOTDETAIL PRIMARY KEY (
	S_SERIALNUM
);


--2. MEMBERINFO 테이블의 M_NICKNAME 컬럼과 외래키 설정
ALTER TABLE PLANINFO ADD CONSTRAINT FK_MEMBERINFO_TO_PLANINFO_1 FOREIGN KEY (
	M_NICKNAME
)
REFERENCES MEMBERINFO (
	M_NICKNAME
);


--PLANDETAIL 외래키 설정
--1. PLANINFO의 P_ROWNUM 컬럼 참조
ALTER TABLE PLANDETAIL ADD CONSTRAINT FK_PLANINFO_TO_PLANDETAIL_1 FOREIGN KEY (
	P_ROWNUM
)
REFERENCES PLANINFO (
	P_ROWNUM
);
--2. SPOTDETAIL의 S_SERIALNUM 컬럼 참조
ALTER TABLE PLANDETAIL ADD CONSTRAINT FK_PLANDETAIL_TO_SPOTDETAIL_1 FOREIGN KEY (
	S_SERIALNUM
)
REFERENCES SPOTDETAIL (
	S_SERIALNUM
);

--ACCOMMODATION
--1. 기본키
ALTER TABLE ACCOMMODATION ADD CONSTRAINT PK_ACCOMMODATION PRIMARY KEY (
    S_SERIALNUM
);
--2. 외래키
ALTER TABLE ACCOMMODATION ADD CONSTRAINT FK_SPOTDETAIL_TO_ACCOM_1 FOREIGN KEY (
	S_SERIALNUM
)
REFERENCES SPOTDETAIL (
	S_SERIALNUM
);

--RESTAURANT 테이블
--1. 기본키 설정
ALTER TABLE RESTAURANT ADD CONSTRAINT PK_RESTAURANT PRIMARY KEY (
	S_SERIALNUM
);
--2. 외래키 설정
ALTER TABLE RESTAURANT ADD CONSTRAINT FK_SPOTDETAIL_TO_RESTAURANT_1 FOREIGN KEY (
	S_SERIALNUM
)
REFERENCES SPOTDETAIL (
	S_SERIALNUM
);

--EVENT 테이블
--1. 기본키 설정
ALTER TABLE EVENT ADD CONSTRAINT PK_EVENT PRIMARY KEY (
	S_SERIALNUM
);
--2. 외래키 설정
ALTER TABLE EVENT ADD CONSTRAINT FK_SPOTDETAIL_TO_EVENT_1 FOREIGN KEY (
	S_SERIALNUM
)
REFERENCES SPOTDETAIL (
	S_SERIALNUM
);

--TRAFFIC 테이블
--1. 기본키 설정
ALTER TABLE TRAFFIC ADD CONSTRAINT PK_TRAFFIC PRIMARY KEY (
	S_SERIALNUM
);
--2. 외래키 설정
ALTER TABLE TRAFFIC ADD CONSTRAINT FK_SPOTDETAIL_TO_TRAFFIC_1 FOREIGN KEY (
	S_SERIALNUM
)
REFERENCES SPOTDETAIL (
	S_SERIALNUM
);



--LIKEINFO TABLE
--1. MEMBERINFO-M_NICKNAME 외래키 설정
ALTER TABLE LIKEINFO ADD CONSTRAINT FK_MEMBERINFO_TO_LIKEINFO_1 FOREIGN KEY (
	M_NICKNAME
)
REFERENCES MEMBERINFO (
	M_NICKNAME
);
--2. PLANINFO - P_ROWNUM 외래키 설정
ALTER TABLE LIKEINFO ADD CONSTRAINT FK_PLANINFO_TO_LIKEINFO_1 FOREIGN KEY (
	P_ROWNUM
)
REFERENCES PLANINFO (
	P_ROWNUM
);