--테이블 전체 삭제쿼리 출력해줌
SELECT 'DROP TABLE "' || TABLE_NAME || '" CASCADE CONSTRAINTS;' FROM user_tables;

DROP TABLE "PLANINFO" CASCADE CONSTRAINTS;
DROP TABLE "MEMBERINFO" CASCADE CONSTRAINTS;
DROP TABLE "TAGLIST" CASCADE CONSTRAINTS;
DROP TABLE "PLANDETAIL" CASCADE CONSTRAINTS;
DROP TABLE "SPOTDETAIL" CASCADE CONSTRAINTS;
DROP TABLE "ACCOMMODATION" CASCADE CONSTRAINTS;
DROP TABLE "RESTAURANT" CASCADE CONSTRAINTS;
DROP TABLE "EVENT" CASCADE CONSTRAINTS;
DROP TABLE "LIKEINFO" CASCADE CONSTRAINTS;
DROP TABLE "TRAFFIC" CASCADE CONSTRAINTS;